export const mapdata = [
  {
    id: '22',
    full_name: '12 Days',
    job_title: '$7,654',
    country: '16.8',
    is_online: '1',
    rating: 3,
    target: 100,
    budget: 47601,
    phone: '22',
    address: '8',
    img_id: 1,
    gender: 'Arrow',
  },
  {
    id: '34',
    full_name: '33 Days',
    job_title: '$23,332',
    country: '2',
    is_online: '1',
    rating: 5,
    target: 40,
    budget: 12253,
    phone: '3.3',
    address: '2',
    img_id: 2,
    gender: 'A Company',
  },
  {
    id: '42',
    full_name: '0 Days',
    job_title: '$64.12',
    country: '1',
    is_online: '1',
    rating: 1,
    target: 66,
    budget: 96183,
    phone: '6',
    address: '408',
    img_id: 6,
    gender: 'B Company',
  },
  {
    id: '42',
    full_name: '0 Day',
    job_title: '$112',
    country: '1',
    is_online: '1',
    rating: 1,
    target: 66,
    budget: 96183,
    phone: '6',
    address: '408',
    img_id: 6,
    gender: 'C Company',
  },
  {
    id: '112',
    full_name: '0 Days',
    job_title: '$211',
    country: '1',
    is_online: '1',
    rating: 1,
    target: 66,
    budget: 96183,
    phone: '6',
    address: '408',
    img_id: 6,
    gender: 'D Company',
  },
];
