
export const horizdata = [
  {
    id: '6.4k',
    full_name: '2.2',
    job_title: '12',
    country: '16.8',
    is_online: '1',
    rating: 3,
    target: 100,
    budget: 47601,
    phone: '22',
    address: '8',
    img_id: 1,
    gender: '1.1',
  },
  {
    id: '2.3K',
    full_name: '33',
    job_title: '8',
    country: '2',
    is_online: '1',
    rating: 5,
    target: 40,
    budget: 12253,
    phone: '3.3',
    address: '2',
    img_id: 2,
    gender: '0',
  },
  {
    id: '42',
    full_name: '0',
    job_title: '0',
    country: '1',
    is_online: '1',
    rating: 1,
    target: 66,
    budget: 96183,
    phone: '6',
    address: '408',
    img_id: 6,
    gender: '0',
  },
];
